version: '3'

services:
  django:
    build: ./app
    image: $COMPOSE_PROJECT_NAME:latest
    container_name: ${COMPOSE_PROJECT_NAME}_django
    env_file:
      - ./envs/prod.env
    restart: unless-stopped
    expose:
      - 8000
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    depends_on:
      - db
      - redis

  db:
    image: "postgres:13-alpine"
    container_name: ${COMPOSE_PROJECT_NAME}_db
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
        - ./envs/prod.env
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  nginx:
    build: ./nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - ${NGINX_EXTERNAL_PORT}:80
    env_file:
      - ./envs/prod.env
    restart: unless-stopped
    depends_on:
      - django

  redis:
    image: "redis"
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    expose:
      - 6379
    env_file:
      ./envs/prod.env
    restart: unless-stopped

  celery_worker:
    image: $COMPOSE_PROJECT_NAME:latest
    container_name: ${COMPOSE_PROJECT_NAME}_celery_worker
    env_file:
      - ./envs/prod.env
    restart: unless-stopped
    command: celery -A app worker -l info
    depends_on:
      - django
      - db
      - redis

  celery_beat:
    image: $COMPOSE_PROJECT_NAME:latest
    container_name: ${COMPOSE_PROJECT_NAME}_celery_beat
    env_file:
      - ./envs/prod.env
    restart: unless-stopped
    command: celery -A app beat -l info
    depends_on:
      - django
      - db
      - redis

  flower:
    image: $COMPOSE_PROJECT_NAME:latest
    container_name: ${COMPOSE_PROJECT_NAME}_flower
    command: celery -A app flower --port=$FLOWER_PORT --broker=$CELERY_BROKER_URL --basic_auth=$FLOWER_USER:$FLOWER_PASS
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    env_file:
      - ./envs/prod.env
    restart: unless-stopped
    depends_on:
      - redis
      - celery_worker
      - celery_beat
      - django

volumes:
  static_volume:
